services:
  app:
    image: personal-page:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-page-app
    command: "uv run gunicorn -b 0.0.0.0:8000 conf.wsgi"
    volumes:
      - "page-static-files:/home/app/files/static"
      - "page-media-files:/home/app/files/media"
      - "page-db:/home/app/files/db"
    restart: always
    env_file: .env
  nginx:
    image: nginx:1.27
    container_name: personal-page-nginx
    ports:
    - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - "page-static-files:/var/html/static"
      - "page-media-files:/var/html/media"
    depends_on:
      - app


volumes:
  page-static-files:
    external: true
  page-media-files:
    external: true
  page-db:
    external: true
